### ISSUE TITLE
xDrip+Bubble

### ISSUE THREAD

**Issue by Archibald-rgb** [NightscoutFoundation/xDrip#1368]
After the developer of the bubble updated the firmware of my device to 2.0 xDrip stopped receiving glucose data. In this case, the program from the developer of the bubble (diabox) receives data from the bubble device as expected.

**Comment by tzachi-dar** [comment]
Please use the latest xdrip nightly.
Issue is solved there.

**Comment by Archibald-rgb** [comment]
Thanks.

**Comment by user-hash** [comment]
Hey, I have same problem as OP, using latest original and nightly versions.
If I download the latest release written on the date OP opened this issue, my Bubble connects without problems.
So looks like, the issue is back in the latest versions.
