### ISSUE TITLE
Follower not getting readings

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#499]
Hi Guys
I've had my son's Libre - MiowMiew - Wear Watch (forced collector) - Android master - Android follower working fine for a couple of months now.
However now, the follower isn't getting any of the readings (watch & master are fine). I've got the latest xDrip dated 6th July on both Androids. Follower Android is version 8.0 & the Master Android is version 7.0
I've tried uninstalling & re-installing, I've cleared the xDdrip cache. I've tried rolling xDrip back to 7th April with the same issue.
Interestingly, on the follower, the xDrip menu only has 4 options - Home - Add Calibration - System Status & Settings.
It could be an issue with v8 (Oreo), but I'm reluctant to roll it back to v7 (nougat) as it needs the phone to be completely wiped, & doesn't appear to be trouble free.
Any ideas what else I can try?
Regards
Ali

**Comment by jamorham** [comment]
It isn't an issue with Android 8

What does the `System Status` menu show in the follower tab?

**Comment by alexmoir1** [comment]
![screenshot_20180708-105051_xdrip](https://user-images.githubusercontent.com/24193604/42538285-7166e328-848f-11e8-98aa-dd4fc955cdd8.jpg)
![screenshot_20180710-221417_xdrip](https://user-images.githubusercontent.com/24193604/42538296-7df5142a-848f-11e8-90ba-89b39b9bb5dd.jpg)
![screenshot_20180710-221939_xdrip](https://user-images.githubusercontent.com/24193604/42538309-850f4104-848f-11e8-8f50-db1d8155b4b7.jpg)
![screenshot_20180710-221851_xdrip](https://user-images.githubusercontent.com/24193604/42538316-8efbdd76-848f-11e8-8751-bf8e7373aded.jpg)

**Comment by jamorham** [comment]
Try repeating the set up for a follower:

https://www.youtube.com/watch?v=LcgjfbYcWkE

**Comment by alexmoir1** [comment]
Tried that & it prompted for an update. Did the update but still the same issue.

**Comment by jamorham** [comment]
It sounds like your google play services is having problems on the master. You can go to Android System App settings, find google play services and clear the data. This will affect quite a few things, for example you'll likely need to relogin to the google play store. I also recommend that when doing this you reboot the phone immediately after clearing the data for google play services.

**Comment by alexmoir1** [comment]
Hi Jamorham
Done that. Same problem I'm afraid.

**Comment by jweismann** [comment]
Hi Jamorham - I can reproduce the issue described by @alexmoir1 on a samsung galaxy s5 as follower and with xdrip from the 21th of july. I even tried to clean all data from google play service on the master and I cleaned all xdrip data on the follower but the problem seems to persist. In the past I always used to use NS and nsclient to sync several xdrip instances but wanted to to try the domestic sync follower out. 

Not sure what I should expect to see on the master in system status - should I see refs to the followers? I don't see that so maybe that could explain something. 

Anyway, I should also mention that if I start nsclient on the follower phone then data start to float to xdrip again.

Let me know if there is something I could try to help pinpoint this one. Thanks.

**Comment by jweismann** [comment]
Update: I found that the QR scan failed and once I managed to get that right it worked as expected. I tried to add two followers to the same master and I noticed that system status on both follower phones showed the right master but one follower only had the master whereas the other follower had both master and follower1 mentioned in followers. Also Master only had follower1 in its system status. Is this as expected or ?

@alexmoir1 - take note at 1:15 in the clip mentioned by @jamorham where it states that it loaded two prefernces - if you don't see this then it might be due to failed QR scan.

**Comment by alexmoir1** [comment]
Yes the 2 QR preferences seem to load fine. Still getting 'Maximum Sync Queue size Exceeded' message on the master, despite clearing google play data.

**Comment by nicola-iuretigh** [comment]
Hi.
Same problem for me too.
One week ago the follower handset stopped receiving data. I've tried to 
+ clean the follower xDrip and reconfigure it,
+ reinstall the app and then reconfigure it
but nothing worked.
I've not ried to clear Google Play Services on the master because (whether right or wrong) I fear to corrupt the master xDrip too and I cannot permit that since I use it to monitor my child at school.

Currently on the follower handset I'm using the Nighscout site (through a browser) uploaded with data by the xDrip master. Unfortunately, this method does not permit to calibrate and and to insert other actions from the follower handset.
It's a pity.

**Comment by alexmoir1** [comment]
I fixed the issue on the Master. Go to Settings - Apps - Xdrip - Storage - Clear Data - Then set up everything again. 
@jamorham any chance you could give the user an option to clear the sync queue data when the 'Maximum Sync Queue size Exceeded' message pops up?

**Comment by darkos8** [comment]
Encountered this 'scary' problem too, clearing app cache alone didn't help, but creating new sync key for followers did help. So like this:
1. Clearing cache (but maybe it is even not necessary, I recommend to start with step 2, only changing sync key and rebooting all devices first, because otherwise you have to go through the Bluetooth data collecting procedure for Master first)
2. Entering a new custom sync key on master device (has to be longer than 16 characters) and copying it and sending to followers to be exactly copied in the sync key field
3. Rebooting master and followers, checking in system status of followers if master Q1 is listed and -expecting only the best!
Good luck

**Comment by ehanoj** [comment]
I have similar problem, I read the thread and test the advice without success.
I tried to use Samsung A3 2017 (SM-A320F, Android 8) as a "XDrip+ Sync Follower" or master for other followers. It failed with "serialize error" and in log is repeatedly "MissedReadingSevice:Aggressively restarting collector service due to lack of reception". Now I see, that probably once in a day get phone full data from master, but I do not why.

The alone connection beetween Libre BT and each from both phones work well.

Tested with latest stable XDrip 20200713.

**Comment by tolot27** [comment]
Please can you try the latest nightly after backing up the database and settings?

**Comment by adanvdo** [comment]
My follower device randomly stopped receiving data yesterday. I updated both master and follower to the latest nightly and that did not fix it.  
It's a little frustrating that you can not reset the sync settings once they are enabled.  The problem with wiping the app data is that in order to get all of your settings back and collector configuration, you have to import ALL settings.  I tried just importing the general and collection settings but those did not include the G6 transmitter number, or any of my display/prediction settings.  
Ultimately, after spending way too much time trying to troubleshoot and fix this, I finally just decided to change the last 2 characters of the Sync Key on both devices.  Sync is now working again.

**Comment by ehanoj** [comment]
> Please can you try the latest nightly after backing up the database and settings?
Thanks for your request. I do not still tested latest night version. But now i see, that problem is with internet connectivity of this phone. Someone wifi has denied or limited access to internet for this phone and also GSM data is not always capable.
As I guess, master/following data transfer is only via Internet not via Bluetooth... It is true reason? I search this in manual but I do not find the capabilities for master/follow data communication.

**Comment by Navid200** [comment]
The work-around for this is to use a Nightscout follower, which will not rely on Google play services.

Since a work-around exists, I am going to close this.  We can always reopen it.  But, keeping issues open (when the developer has clearly stated what the cause of the problem is being out of his hands) will take attention from issues that have no work-around.  So, I hope you wouldn't re-open it.

If you need help setting up Nightscout, you can get support from many different sources.
One is this this facebook group:
https://www.facebook.com/groups/cgminthecloud

**Comment by MoonlitMarsh** [comment]
Anyone else encountering this problem in 2024? Sync was working fine until yesterday. 
I tried all the fixes listed in this thread, to no avail. My mom is very dependent on this sync function. 
Any advice would be appreciated, thank you!

**Comment by jonprogers** [comment]
> Anyone else encountering this problem in 2024? Sync was working fine until yesterday. I tried all the fixes listed in this thread, to no avail. My mom is very dependent on this sync function. Any advice would be appreciated, thank you!

https://github.com/NightscoutFoundation/xDrip/discussions/3580

**Comment by Eleni38** [comment]
I have the same problem today....pls if anyone knows something tell me

**Comment by AnibalPellino** [comment]
Same problem appears yesterday and nothing seems to work. We have triesr reinstal, install older version, etc, but nothing works.

**Comment by jonprogers** [comment]
> Same problem appears yesterday and nothing seems to work. We have triesr reinstal, install older version, etc, but nothing works.

as above see here...
https://github.com/NightscoutFoundation/xDrip/discussions/3580

**Comment by vawlk** [comment]
yes, same problem as of yesterday. i changed to nightscout.follower for now.

**Comment by Navid200** [comment]
Just in case you have not seen, the issue has been identified and is being fixed.
This contains all the relevant discussions: https://github.com/NightscoutFoundation/xDrip/discussions/3580  

Posting in this old issue does not help in any shape or form.
